FROM python:3.12

WORKDIR /app

COPY . /app

RUN echo 'api { credentials {"access_key": "<KEY>", "secret_key": "<KEY>"} }' > ~/clearml.conf

RUN python -m pip install .

EXPOSE 8000

CMD ["python", "-m", "gigmate.serve"]