[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gigmate"
version = "0.1.0"
description = "MIDI generation"
authors = [
    { name = "Michele Lugano", email = "michele.lugano@gmail.com" },
]
dependencies = [
    "clearml",
    "tqdm",
    "scikit-learn",
    "pickle",
    "torch",
    "torchinfo",
    "torchmetrics",
    "symusic",
    "miditok",
]
requires-python = ">=3.9"
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
]

[tool.hatch.build.targets.wheel]
packages = ["gigmate"]


[tool.hatch.version]
[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 100
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 100