workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-8
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
      #machineType: a2-highgpu-1g
    replicaCount: 1
    containerSpec:
      imageUri: us-central1-docker.pkg.dev/${PROJECT_ID}/gigmate-training/training-image:${COMMIT_SHA}
      command:
        - python
        - -m
        - gigmate.train
      args:
        - --job-dir=gs://${GCP_BUCKET}/gigmate_training_${COMMIT_SHA}