workerPoolSpecs:
  - machineSpec:
      #machineType: n1-standard-4
      # acceleratorType: NVIDIA_TESLA_T4
      # acceleratorCount: 1
      machineType: g2-standard-8
      acceleratorType: NVIDIA_L4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: ${IMAGE_NAME}
      args:
        - --job-dir=gs://$GCP_BUCKET/gigmate_training_$COMMIT_SHA
      env:
        - name: PROJECT_ID
          value: $PROJECT_ID
        - name: COMMIT_SHA
          value: $COMMIT_SHA
        - name: GCP_BUCKET
          value: $GCP_BUCKET