name: Deploy model on Docker Hub

on:
  push:
    branches:
      - 'release'

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_URI: energydrink9/gigmate

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image
      env:
        IMAGE_NAME: $DOCKER_HUB_URI
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login --username energydrink9 --password-stdin
        docker build -t "${{ env.IMAGE_NAME }}:${{ github.sha }}" -t "${{ env.IMAGE_NAME }}:latest" -f Dockerfile.serve .
        docker push ${{ env.IMAGE_NAME }} --all-tags

    # - name: Get latest image tag
    #   id: get_tag
    #   run: |
    #     LATEST_TAG=$(docker pull $DOCKER_HUB_URI | grep -oP '(?<=:)[^ ]+')
    #     echo "image_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

    # - name: Submit deployment
    #   env:
    #     IMAGE_NAME: $DOCKER_HUB_URI:${{ steps.get_tag.outputs.image_tag }}
    #   run: |
    #     # Deployment commands for your service
