name: Deploy model on Serverless platform

on:
  push:
    branches:
      - 'release'

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      GCP_BUCKET: gigmate-deployment-outputs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
  
    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      env:
        IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gigmate-training/deployment-image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest -f Dockerfile.serve .
        docker push $IMAGE_NAME --all-tags

    # - name: Get latest image tag
    #   id: get_tag
    #   run: |
    #     if [ "${{ steps.dockerfile_changes.outputs.changed }}" == "true" ]; then
    #     echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
    #     else
    #     LATEST_TAG=$(gcloud artifacts docker tags list us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gigmate-training/deployment-image --limit=1 --format='value(TAG)')
    #     echo "image_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
    #     fi

    # - name: Submit Vertex AI deployment
    #   env:
    #     PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    #     COMMIT_SHA: ${{ steps.get_tag.outputs.image_tag }}
    #     GCP_BUCKET: ${{ env.GCP_BUCKET }}
    #     IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gigmate-training/deployment-image:${{ steps.get_tag.outputs.image_tag }}
    #   run: |
    #     envsubst < vertex_config.deployment.yaml > vertex_config_temp.yaml
    #     gcloud ai custom-jobs create \
    #       --region=us-central1 \
    #       --display-name=gigmate_deployment_job_${{ github.sha }} \
    #       --config=vertex_config_temp.yaml
