name: Train Model on Google Cloud Vertex AI

on:
  push:
    branches:
      - 'training/**'

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      GCP_BUCKET: gigmate-training-outputs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
  
    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      env:
        IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigmate-training:${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Submit Vertex AI training job
      env:
        IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/gigmate-training:${{ github.sha }}
      run: |
        gcloud ai custom-jobs create \
          --region=us-central1 \
          --display-name=gigmate_training_job_${{ github.sha }} \
          --config=vertex_config.yaml \
          --set-env-variables=PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},COMMIT_SHA=${{ github.sha }},GCP_BUCKET=${{ env.GCP_BUCKET }}
